### ISSUE TITLE
Numeric | 'Unit' isn't working inside a rule

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#319]
This would fail:

```ruby
rule 'x' do
  every :second
  run { logger.info("X: #{0 | 'W'}") }
end
```

Or it could be a `changed` trigger or any other trigger apart from on_start

Error message:
```
21:57:43.268 [ERROR] [y.OpenHAB::DSL::Rules::AutomationRule] - wrong number of arguments (given 3, expected 1) (ArgumentError)
In rule: x
/openhab/conf/automation/jsr223/ruby/personal/test.rb:94:in `method_missing'
/openhab/conf/automation/jsr223/ruby/personal/test.rb:67:in `block in <main>'
```

This works, however:
```ruby
rule 'x' do
  on_start
  run { logger.info("X: #{0 | 'W'}") }
end
```

**Comment by ccutrer** [comment]
so the root of the issue is that somehow `::QuantityType`, outside the rule is `Java::OrgOpenhabCoreLibraryTypes::QuantityType` (the ruby class that proxies to the java class and is usable to actually create ruby objects from, and  that we have added all our extensions to), but inside the rule (where `self` is still `main`, as it should be) it's `class org.openhab.core.library.types.QuantityType` (the ruby object that represents the java class and is more of a metadata thing). I'm not 100% sure how it's getting overwritten, but I suspect it's one of the many `java_imports` we have thrown around. I can fix this particular bug relatively quickly, then I'll dig deeper on why the constant is getting overwritten.
