### ISSUE TITLE
Timers don't always get cancelled on script reloads

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#366]
I am scratching my head about scriptunload / automatic cancelling of the timers. It doesn't seem to happen reliably, i.e. sometimes the outstanding/active timers get cancelled but sometimes they don't seem to get cancelled.

Here's how to reproduce it: create a script
```ruby
require 'openhab'
# x
t = Time.now
after(1.minute) { logger.error("Time's up #{t}") }
```

I just kept adding x to the comments and re-saving it (so that the file is different and therefore gets reloaded by openhab), before the 1 minute had passed.

In theory, it should cancel all outstanding timers, and you'll only see ONE "Time's up <timestamp>" in the log once you've stopped re-saving the file for a minute. But if you re-save it often enough (and within less than 1 minute), you'll see a bunch of log entries with different timestamps which indicates that those timers didn't get cancelled, and multiple timers got executed.

_Originally posted by @jimtng in https://github.com/boc-tothefuture/openhab-jruby/issues/316#issuecomment-956306110_

**Comment by boc-tothefuture** [comment]
Can you add a logging statement after the timer is added?  I am curious if scriptUnloaded is being called each time? OpenHAB is watching file events.. it is certainly possible the deletions or reloads are getting lost if it is happening too often.  Are you seeing it in production or just when you make this test?

**Comment by ccutrer** [comment]
I can't even get the test for "Scenario: Timers in rules are cancelled if the script is removed" to pass for me locally. Log looks like this:

```
2021-11-01 20:08:46.443 [TRACE] [jsr223.jruby.Object                 ] - Script loaded: file:/Users/cody/src/openhab-jruby/tmp/openhab/conf/automation/jsr223/ruby/personal/cucumber_test20211101-21439-1wdeaa4.rb
2021-11-01 20:08:46.444 [DEBUG] [rt.internal.loader.ScriptFileWatcher] - Script loaded: /Users/cody/src/openhab-jruby/tmp/openhab/conf/automation/jsr223/ruby/personal/cucumber_test20211101-21439-1wdeaa4.rb
2021-11-01 20:08:48.940 [INFO ] [utomation.rest.internal.RuleResource] - Received HTTP DELETE request at 'rules/32732332-9a0b-475b-b783-d1d3a9ee91a3' for the unknown rule '32732332-9a0b-475b-b783-d1d3a9ee91a3'.
2021-11-01 20:08:51.444 [TRACE] [r223.jruby.org.jruby.gen.RubyObject4] - Removing org.openhab.core.model.script.internal.actions.TimerImpl@5f7b4cab from timers
2021-11-01 20:08:51.445 [INFO ] [jsr223.jruby.Object                 ] - Timer Fired
2021-11-01 20:08:55.711 [DEBUG] [rt.internal.loader.ScriptFileWatcher] - Dequeued file:/Users/cody/src/openhab-jruby/tmp/openhab/conf/automation/jsr223/ruby/personal/cucumber_test20211101-21439-1wdeaa4.rb
2021-11-01 20:08:55.712 [TRACE] [jsr223.jruby.Object                 ] - Script unloaded
2021-11-01 20:08:55.712 [TRACE] [r223.jruby.org.jruby.gen.RubyObject4] - Canceling 0 timers
2021-11-01 20:08:55.713 [TRACE] [automation.internal.RuleEventFactory] - creating ruleEvent of type: RuleRemovedEvent
```

it looks like the callback is called, but it waits until the timer runs first.

**Comment by jimtng** [comment]
I'm seeing this in my production environment. I have a test.rb file that I use for testing things.
I edited the timers file and inserted a logger when it's being cleared. That logger didn't get called all the time, only some of the time, maybe 1 out of 5-10. In other words, scriptUnloaded isn't being called all the time.

**Comment by boc-tothefuture** [comment]
> I can't even get the test for "Scenario: Timers in rules are cancelled if the script is removed" to pass for me locally. Log looks like this:
> 
> ```
> 2021-11-01 20:08:46.443 [TRACE] [jsr223.jruby.Object                 ] - Script loaded: file:/Users/cody/src/openhab-jruby/tmp/openhab/conf/automation/jsr223/ruby/personal/cucumber_test20211101-21439-1wdeaa4.rb
> 2021-11-01 20:08:46.444 [DEBUG] [rt.internal.loader.ScriptFileWatcher] - Script loaded: /Users/cody/src/openhab-jruby/tmp/openhab/conf/automation/jsr223/ruby/personal/cucumber_test20211101-21439-1wdeaa4.rb
> 2021-11-01 20:08:48.940 [INFO ] [utomation.rest.internal.RuleResource] - Received HTTP DELETE request at 'rules/32732332-9a0b-475b-b783-d1d3a9ee91a3' for the unknown rule '32732332-9a0b-475b-b783-d1d3a9ee91a3'.
> 2021-11-01 20:08:51.444 [TRACE] [r223.jruby.org.jruby.gen.RubyObject4] - Removing org.openhab.core.model.script.internal.actions.TimerImpl@5f7b4cab from timers
> 2021-11-01 20:08:51.445 [INFO ] [jsr223.jruby.Object                 ] - Timer Fired
> 2021-11-01 20:08:55.711 [DEBUG] [rt.internal.loader.ScriptFileWatcher] - Dequeued file:/Users/cody/src/openhab-jruby/tmp/openhab/conf/automation/jsr223/ruby/personal/cucumber_test20211101-21439-1wdeaa4.rb
> 2021-11-01 20:08:55.712 [TRACE] [jsr223.jruby.Object                 ] - Script unloaded
> 2021-11-01 20:08:55.712 [TRACE] [r223.jruby.org.jruby.gen.RubyObject4] - Canceling 0 timers
> 2021-11-01 20:08:55.713 [TRACE] [automation.internal.RuleEventFactory] - creating ruleEvent of type: RuleRemovedEvent
> ```
> 
> it looks like the callback is called, but it waits until the timer runs first.

That 'dequeued' file is from OpenHAB itself - I think you hit this issue before where the file watcher was slow on your system because it polled based on your operating system.  If we don't get notified with script unloaded then there is not much we can do.

**Comment by ccutrer** [comment]
🤦  you're totally right

**Comment by boc-tothefuture** [comment]
> I'm seeing this in my production environment. I have a test.rb file that I use for testing things. I edited the timers file and inserted a logger when it's being cleared. That logger didn't get called all the time, only some of the time, maybe 1 out of 5-10. In other words, scriptUnloaded isn't being called all the time.

Check for the ScriptFileWatcher line that @ccutrer  had and see if that is getting called.  See if yours is an operating system/openhab notification issue?

**Comment by boc-tothefuture** [comment]
> > I'm seeing this in my production environment. I have a test.rb file that I use for testing things. I edited the timers file and inserted a logger when it's being cleared. That logger didn't get called all the time, only some of the time, maybe 1 out of 5-10. In other words, scriptUnloaded isn't being called all the time.
> 
> Check for the ScriptFileWatcher line that @ccutrer had and see if that is getting called. See if yours is an operating system/openhab notification issue?

@jimtng can you check the ScriptFileWatcher line in your test and report back what you see?

**Comment by jimtng** [comment]
I've set the logging level for ScriptFileWatcher to to DEBUG

```
log:set DEBUG org.openhab.core.automation.module.script.rulesupport
```

Inside script_handling.rb OpenHAB::Core::ScriptHandling::scriptUnloaded method, I changed logger.trace to logger.error so I can see it without seeing all the other trace logs.

Then I modified and saved my test script 6 times, in about 2-3 seconds interval. ScriptFileWatcher itself is reliably dequeuing and then reloading the script. 
```
10:18:34.513 [DEBUG] [ort.internal.loader.ScriptFileWatcher] - Dequeued file:/openhab/conf/automation/jsr223/ruby/personal/test.rb
10:18:34.648 [INFO ] [ort.internal.loader.ScriptFileWatcher] - Loading script '/openhab/conf/automation/jsr223/ruby/personal/test.rb'
10:18:35.546 [INFO ] [jsr223.jruby.OpenHAB                 ] - OpenHAB JRuby Scripting Library Version 4.10.1 Loaded
10:18:35.564 [DEBUG] [ort.internal.loader.ScriptFileWatcher] - Script loaded: /openhab/conf/automation/jsr223/ruby/personal/test.rb
10:18:41.550 [DEBUG] [ort.internal.loader.ScriptFileWatcher] - Dequeued file:/openhab/conf/automation/jsr223/ruby/personal/test.rb
10:18:41.553 [ERROR] [jsr223.jruby.Object                  ] - **Script unloaded**
10:18:41.555 [INFO ] [ort.internal.loader.ScriptFileWatcher] - Loading script '/openhab/conf/automation/jsr223/ruby/personal/test.rb'
10:18:42.373 [INFO ] [jsr223.jruby.OpenHAB                 ] - OpenHAB JRuby Scripting Library Version 4.10.1 Loaded
10:18:42.379 [DEBUG] [ort.internal.loader.ScriptFileWatcher] - Script loaded: /openhab/conf/automation/jsr223/ruby/personal/test.rb
10:18:47.099 [DEBUG] [ort.internal.loader.ScriptFileWatcher] - Dequeued file:/openhab/conf/automation/jsr223/ruby/personal/test.rb
10:18:47.212 [INFO ] [ort.internal.loader.ScriptFileWatcher] - Loading script '/openhab/conf/automation/jsr223/ruby/personal/test.rb'
10:18:48.119 [INFO ] [jsr223.jruby.OpenHAB                 ] - OpenHAB JRuby Scripting Library Version 4.10.1 Loaded
10:18:48.124 [DEBUG] [ort.internal.loader.ScriptFileWatcher] - Script loaded: /openhab/conf/automation/jsr223/ruby/personal/test.rb
10:18:54.172 [DEBUG] [ort.internal.loader.ScriptFileWatcher] - Dequeued file:/openhab/conf/automation/jsr223/ruby/personal/test.rb
10:18:54.283 [INFO ] [ort.internal.loader.ScriptFileWatcher] - Loading script '/openhab/conf/automation/jsr223/ruby/personal/test.rb'
10:18:55.070 [INFO ] [jsr223.jruby.OpenHAB                 ] - OpenHAB JRuby Scripting Library Version 4.10.1 Loaded
10:18:55.075 [DEBUG] [ort.internal.loader.ScriptFileWatcher] - Script loaded: /openhab/conf/automation/jsr223/ruby/personal/test.rb
10:19:01.857 [DEBUG] [ort.internal.loader.ScriptFileWatcher] - Dequeued file:/openhab/conf/automation/jsr223/ruby/personal/test.rb
10:19:02.043 [INFO ] [ort.internal.loader.ScriptFileWatcher] - Loading script '/openhab/conf/automation/jsr223/ruby/personal/test.rb'
10:19:03.033 [INFO ] [jsr223.jruby.OpenHAB                 ] - OpenHAB JRuby Scripting Library Version 4.10.1 Loaded
10:19:03.038 [DEBUG] [ort.internal.loader.ScriptFileWatcher] - Script loaded: /openhab/conf/automation/jsr223/ruby/personal/test.rb
10:19:09.750 [DEBUG] [ort.internal.loader.ScriptFileWatcher] - Dequeued file:/openhab/conf/automation/jsr223/ruby/personal/test.rb
10:19:09.752 [ERROR] [jsr223.jruby.Object                  ] - **Script unloaded**
10:19:09.754 [INFO ] [ort.internal.loader.ScriptFileWatcher] - Loading script '/openhab/conf/automation/jsr223/ruby/personal/test.rb'
10:19:10.576 [INFO ] [jsr223.jruby.OpenHAB                 ] - OpenHAB JRuby Scripting Library Version 4.10.1 Loaded
10:19:10.583 [DEBUG] [ort.internal.loader.ScriptFileWatcher] - Script loaded: /openhab/conf/automation/jsr223/ruby/personal/test.rb
10:19:42.376 [ERROR] [jsr223.jruby.Object                  ] - Time's up 2021-11-04 10:18:42 +1000
10:19:48.121 [ERROR] [jsr223.jruby.Object                  ] - Time's up 2021-11-04 10:18:48 +1000
10:19:55.072 [ERROR] [jsr223.jruby.Object                  ] - Time's up 2021-11-04 10:18:55 +1000
10:20:10.579 [ERROR] [jsr223.jruby.Object                  ] - Time's up 2021-11-04 10:19:10 +1000
```

Notice there were two **Script unloaded** and there were four logs of "Time's up". There should have been 6 "Script unloaded" and one "Time's up" from the very last reload.

**Comment by jimtng** [comment]
I added a TRACE log:
```
log:set TRACE org.openhab.core.automation.module
```

and I got this in my log:
```
10:34:17.384 [DEBUG] [ort.internal.loader.ScriptFileWatcher] - Dequeued file:/openhab/conf/automation/jsr223/ruby/personal/test.rb
10:34:17.491 [TRACE] [ript.internal.ScriptEngineManagerImpl] - scriptUnloaded() is not defined in the script
```


https://github.com/openhab/openhab-core/blob/b02dfdc0677dbf49a78d82b34d049c83281cf890/bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/ScriptEngineManagerImpl.java#L195-L212

**Comment by jimtng** [comment]
> I can't even get the test for "Scenario: Timers in rules are cancelled if the script is removed" to pass for me locally.

ditto

My dev environment is OSX 12.0.1
My production environment is a Docker on Centos 8

It is not the case that the OS/openhab is missing the file change notifications. On the contrary, the OS and openhab did catch the file change notification reliably, because my scripts get reloaded every time I made changes / saved it.

**Comment by boc-tothefuture** [comment]
I can recreate this problem with a single edit.. sometimes scriptUnloaded gets invoked but most times it doesn't..

What is interesting is that during tests it always gets invoked.  It is like if the file is new and then removed we don't hit this problem, but if the same file is edited we hit it.

**Comment by jimtng** [comment]
Can we use this? https://github.com/openhab/openhab-core/pull/1264

**Comment by boc-tothefuture** [comment]
Let me look at that!
BTW, I can reproduce this without our library.  Can you check that as well?

Just create a script, don't do a require 'openhab'.  
Implement

```
def scriptUnloaded
  puts "Called unloaded"
end
```

When I do that, it sometimes gets called (usually the first time?) but then it says on subsequent edits that the method isn't available.

**Comment by jimtng** [comment]
> Can we use this? [openhab/openhab-core#1264](https://github.com/openhab/openhab-core/pull/1264)

I've been trying to use this, but couldn't make it work. Basically it just needs this:

```ruby
def my_script_unloaded
  logger.error('My UNLOAD')
end
$lifecycleTracker.add_dispose_hook(-> { my_script_unload })
```
 BUT, the "Disposable" interface is not accessible :(



> BTW, I can reproduce this without our library. Can you check that as well?
> 
> Just create a script, don't do a require 'openhab'. Implement
> 
> ```
> def scriptUnloaded
>   puts "Called unloaded"
> end
> ```
> 
> When I do that, it sometimes gets called (usually the first time?) but then it says on subsequent edits that the method isn't available.

I'm sure I'd see the same result. This is not caused by our library.

**Comment by jimtng** [comment]
Pinging @jpg0 - could you give some examples on how to utilise the `lifecycleTracker` please?

**Comment by boc-tothefuture** [comment]
@jimtng it is package private so you should be able to create a class in that same package and them implement dispose on it.

I can't look at it more right now but I took a quick stab:

```
require 'java'

puts $lifecycleTracker.class
puts $lifecycleTracker.class.inspect

module Java::OrgOpenhabCoreAutomationModuleScriptInternalDefaultscope
    class Foo < LifecycleScriptExtensionProvider
#        include org.openhab.core.automation.module.script.internal.defaultscope.LifecycleScriptExtensionProvider
        include Java::OrgOpenhabCoreAutomationModuleScriptInternalDefaultscope::LifecycleScriptExtensionProvider::Disposable
        def dispose
            puts "disposed?"
        end
    end
end


$lifecycleTracker.add_dispose_hook( Java::OrgOpenhabCoreAutomationModuleScriptInternalDefaultscopeFoo.new )

```

I can't get the class right for including "Disable" to implement the interface.   Here are the instructions:
https://github.com/jruby/jruby/wiki/CallingJavaFromJRuby#implementing-java-interfaces-in-jruby

**Comment by jimtng** [comment]
Technically one should be able to just call `$lifecycleTracker.add_dispose_hook { my_script_unloaded }` because Disposable is a `functionalinterface`

I haven't had much luck with your suggestion. One thing I found is you need to use all lower case

**Comment by jpg0** [comment]
You can see this class used at https://github.com/jpg0/ohj/blob/master/osgi.js#L97

It is used from JS via a functional interface, and the JS engine doesn't appear to care about the package security of `Disposable` in this case. It looks like you are trying to do the right thing here and the challenges you have are with Ruby/Java interop. (Also I have no problem with you making the `Disposable` interface public, but I have no rights to merge it.)

**Comment by ccutrer** [comment]
I think JRuby has a bug here, trying to access the internal package with the nested interface. I was able to find the interface from ruby, but not without jumping through hoops:

```ruby
class A
  # _cannot_ use org.openhab.core.automation.module.script.internal.defaultscope.LifecycleScriptExtensionProvider
  # nor can you java_import it as such
  provider = Java::OrgOpenhabCoreAutomationModuleScriptInternalDefaultscope::LifecycleScriptExtensionProvider
  # provider.constants returns [:LifecycleTracker]
  disposable = provider.java_class.get_declared_classes.find { |i| i.name.end_with?("$Disposable") }.ruby_class
  logger.info(disposable) # => #<Module:0x69f0c0c3> (i.e. an anonymous module)
  include disposable

  def dispose
    logger.error("disposed!")
  end
end
```

however, when I actually try to register the callback (`$lifecycleTracker.add_dispose_hook(A.new)`) I get a huge error in the log:

```
2021-11-06 16:15:51.623 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.lang.NoClassDefFoundError: org/openhab/core/automation/module/script/internal/defaultscope/LifecycleScriptExtensionProvider$Disposable
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]
        at org.jruby.util.ClassDefiningJRubyClassLoader.defineClass(ClassDefiningJRubyClassLoader.java:53) ~[?:?]
        at org.jruby.java.codegen.RealClassGenerator.defineRealImplClass(RealClassGenerator.java:551) ~[?:?]
        at org.jruby.java.codegen.RealClassGenerator.createRealImplClass(RealClassGenerator.java:161) ~[?:?]
        at org.jruby.javasupport.Java.generateRealClass(Java.java:1612) ~[?:?]
        at org.jruby.java.proxies.JavaInterfaceTemplate$3.allocate(JavaInterfaceTemplate.java:299) ~[?:?]
        at org.jruby.RubyClass.allocate(RubyClass.java:230) ~[?:?]
        at org.jruby.RubyClass.newInstance(RubyClass.java:878) ~[?:?]
        at org.jruby.RubyClass$INVOKER$i$newInstance.call(RubyClass$INVOKER$i$newInstance.gen) ~[?:?]
        at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroOrNBlock.call(JavaMethod.java:332) ~[?:?]
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:351) ~[?:?]
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:144) ~[?:?]
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:345) ~[?:?]
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72) ~[?:?]
        at org.jruby.ir.interpreter.Interpreter.INTERPRET_ROOT(Interpreter.java:96) ~[?:?]
        at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:81) ~[?:?]
        at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:30) ~[?:?]
        at org.jruby.ir.IRTranslator.execute(IRTranslator.java:42) ~[?:?]
        at org.jruby.Ruby.runInterpreter(Ruby.java:1292) ~[?:?]
        at org.jruby.Ruby.runInterpreter(Ruby.java:1296) ~[?:?]
        at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:119) ~[?:?]
        at org.jruby.embed.jsr223.JRubyEngine.doEval(JRubyEngine.java:97) ~[?:?]
        at org.jruby.embed.jsr223.JRubyEngine.eval(JRubyEngine.java:124) ~[?:?]
        at org.jruby.embed.jsr223.JRubyEngine.eval(JRubyEngine.java:150) ~[?:?]
        at org.openhab.core.automation.module.script.internal.ScriptEngineManagerImpl.loadScript(ScriptEngineManagerImpl.java:177) ~[?:?]
        at org.openhab.core.automation.module.script.rulesupport.internal.loader.ScriptFileWatcher.importFile(ScriptFileWatcher.java:216) ~[?:?]
        at org.openhab.core.automation.module.script.rulesupport.internal.loader.ScriptFileWatcher.lambda$1(ScriptFileWatcher.java:195) ~[?:?]
        at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
        at org.openhab.core.automation.module.script.rulesupport.internal.loader.ScriptFileWatcher.importFileWhenReady(ScriptFileWatcher.java:193) ~[?:?]
        at org.openhab.core.automation.module.script.rulesupport.internal.loader.ScriptFileWatcher.processWatchEvent(ScriptFileWatcher.java:170) ~[?:?]
        at org.openhab.core.service.WatchQueueReader.lambda$3(WatchQueueReader.java:322) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.ClassNotFoundException: org.openhab.core.automation.module.script.internal.defaultscope.LifecycleScriptExtensionProvider$Disposable
        at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        ... 38 more
```

**Comment by ccutrer** [comment]
note that if you _just_ do `$lifecycleTracker.add_dispose_hook { logger.error("disposed") }`, the logged error is similar:

```
2021-11-06 16:18:57.766 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.lang.NoClassDefFoundError: org/openhab/core/automation/module/script/internal/defaultscope/LifecycleScriptExtensionProvider$Disposable
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]
        at org.jruby.util.ClassDefiningJRubyClassLoader.defineClass(ClassDefiningJRubyClassLoader.java:53) ~[?:?]
        at org.jruby.java.codegen.RealClassGenerator.defineOldStyleImplClass(RealClassGenerator.java:295) ~[?:?]
        at org.jruby.java.codegen.RealClassGenerator.createOldStyleImplClass(RealClassGenerator.java:148) ~[?:?]
        at org.jruby.javasupport.Java.newInterfaceImpl(Java.java:1457) ~[?:?]
        at org.jruby.java.proxies.JavaInterfaceTemplate.newInterfaceProxy(JavaInterfaceTemplate.java:313) ~[?:?]
        at org.jruby.java.proxies.JavaInterfaceTemplate.access$100(JavaInterfaceTemplate.java:61) ~[?:?]
        at org.jruby.java.proxies.JavaInterfaceTemplate$InterfaceProxyFactory.call(JavaInterfaceTemplate.java:261) ~[?:?]
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:198) ~[?:?]
        at org.jruby.RubyClass.finvoke(RubyClass.java:568) ~[?:?]
        at org.jruby.runtime.Helpers.invoke(Helpers.java:649) ~[?:?]
        at org.jruby.javasupport.JavaUtil.convertProcToInterface(JavaUtil.java:266) ~[?:?]
        at org.jruby.RubyBasicObject.defaultToJava(RubyBasicObject.java:871) ~[?:?]
        at org.jruby.RubyBasicObject.toJava(RubyBasicObject.java:850) ~[?:?]
        at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:81) ~[?:?]
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:329) ~[?:?]
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:87) ~[?:?]
        at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:94) ~[?:?]
        at org.jruby.ir.instructions.CallBase.interpret(CallBase.java:546) ~[?:?]
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:361) ~[?:?]
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72) ~[?:?]
        at org.jruby.ir.interpreter.Interpreter.INTERPRET_ROOT(Interpreter.java:96) ~[?:?]
        at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:81) ~[?:?]
        at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:30) ~[?:?]
        at org.jruby.ir.IRTranslator.execute(IRTranslator.java:42) ~[?:?]
        at org.jruby.Ruby.runInterpreter(Ruby.java:1292) ~[?:?]
        at org.jruby.Ruby.runInterpreter(Ruby.java:1296) ~[?:?]
        at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:119) ~[?:?]
        at org.jruby.embed.jsr223.JRubyEngine.doEval(JRubyEngine.java:97) ~[?:?]
        at org.jruby.embed.jsr223.JRubyEngine.eval(JRubyEngine.java:124) ~[?:?]
        at org.jruby.embed.jsr223.JRubyEngine.eval(JRubyEngine.java:150) ~[?:?]
        at org.openhab.core.automation.module.script.internal.ScriptEngineManagerImpl.loadScript(ScriptEngineManagerImpl.java:177) ~[?:?]
        at org.openhab.core.automation.module.script.rulesupport.internal.loader.ScriptFileWatcher.importFile(ScriptFileWatcher.java:216) ~[?:?]
        at org.openhab.core.automation.module.script.rulesupport.internal.loader.ScriptFileWatcher.lambda$1(ScriptFileWatcher.java:195) ~[?:?]
        at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
        at org.openhab.core.automation.module.script.rulesupport.internal.loader.ScriptFileWatcher.importFileWhenReady(ScriptFileWatcher.java:193) ~[?:?]
        at org.openhab.core.automation.module.script.rulesupport.internal.loader.ScriptFileWatcher.processWatchEvent(ScriptFileWatcher.java:170) ~[?:?]
        at org.openhab.core.service.WatchQueueReader.lambda$3(WatchQueueReader.java:322) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.ClassNotFoundException: org.openhab.core.automation.module.script.internal.defaultscope.LifecycleScriptExtensionProvider$Disposable
        at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        ... 45 more
```

**Comment by jimtng** [comment]
I am not having much luck with making lifecycleTracker to work.

Going with a different avenue, `scriptUnloaded` is reliably called in jython scripts, but reliably not called in jruby. I don't understand why.

**Comment by jpg0** [comment]
I suspect the problem may be with the package:

org.openhab.core.automation.module.script._**internal**_.defaultscope.LifecycleScriptExtensionProvider$Disposable

Anything within an **internal** package is by default not exported outside its bundle. This would mean that it would only be accessible from the classloader of the bundle containing the class, which is the automation module. This makes me wonder how the JS code is working! There is certainly some classloader trickery in the JS code to work around Graal not playing nicely with OSGi, so maybe that is allowing it work.

The upshot is that if you move the class to a different (non-internal, I'd just remove that segment) package, then it _should_ work.

**Comment by jimtng** [comment]
> I suspect the problem may be with the package:
> 
> org.openhab.core.automation.module.script._**internal**_.defaultscope.LifecycleScriptExtensionProvider$Disposable
> 
> Anything within an **internal** package is by default not exported outside its bundle. This would mean that it would only be accessible from the classloader of the bundle containing the class, which is the automation module. This makes me wonder how the JS code is working! There is certainly some classloader trickery in the JS code to work around Graal not playing nicely with OSGi, so maybe that is allowing it work.
> 
> The upshot is that if you move the class to a different (non-internal, I'd just remove that segment) package, then it _should_ work.

Thank you for that tip! I moved LifecycleScriptExtensionProvider out of internal and also made Disposable public, and now it is working from jruby.

I will submit a PR and hope it gets merged.

**Comment by boc-tothefuture** [comment]
> I am not having much luck with making lifecycleTracker to work. I tried making Disposable public and recompile the relevant bundle in openhab-core, but that didn't seem to make a difference for jruby.
> 
> Going back to `scriptUnloaded`, it is is reliably called in jython scripts, but reliably not called in jruby. I don't understand why. 

It is not they scriptUnloaded isn't called, it ends up being undefined (despite being defined) on most occasions.

**Comment by jimtng** [comment]
My PR to make `$lifecycleTracker.add_dispose_hook` to work has been merged. However, this doesn't help us for OH 3.0 and OH 3.1. I have been working on troubleshooting the scriptLoaded/scriptUnloaded issue in the mean time.
