### ISSUE TITLE
PlayerItem rewinding? fastforwarding? error

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#413]
I was running received_command.feature:23 `Scenario: Rule supports helper predicates for named commands`

```
bundle exec cucumber features/received_command.feature:23
```

I came across this error:
```
15:22:16.852 [ERROR] [yobj.OpenHAB.DSL.Rules.AutomationRule] - undefined method `fastforward?' for #<Java::OrgOpenhabCoreItemsEvents::ItemCommandEvent:0x5844134d>
Did you mean?  fast_forward? (NoMethodError)
In rule: Execute rule when item received command
/Users/jimmy/Projects/openhab-jruby/tmp/openhab/conf/automation/jsr223/ruby/personal/cucumber_test20211121-93046-1li7ov4.rb:11:in `block in <main>'
org/jruby/RubyArray.java:1865:in `each'
/Users/jimmy/Projects/openhab-jruby/tmp/openhab/conf/automation/jsr223/ruby/personal/cucumber_test20211121-93046-1li7ov4.rb:10:in `block in <main>'
org/jruby/RubyBasicObject.java:2663:in `instance_exec'
/Users/jimmy/Projects/openhab-jruby/tmp/openhab/conf/automation/lib/ruby/gem_home/gems/openhab-scripting-4.14.1/lib/openhab/dsl/rules/automation_rule.rb:385:in `process_run_task'
/Users/jimmy/Projects/openhab-jruby/tmp/openhab/conf/automation/lib/ruby/gem_home/gems/openhab-scripting-4.14.1/lib/openhab/dsl/rules/automation_rule.rb:330:in `process_task'
/Users/jimmy/Projects/openhab-jruby/tmp/openhab/conf/automation/lib/ruby/gem_home/gems/openhab-scripting-4.14.1/lib/openhab/dsl/rules/automation_rule.rb:314:in `process_queue'
/Users/jimmy/Projects/openhab-jruby/tmp/openhab/conf/automation/lib/ruby/gem_home/gems/openhab-scripting-4.14.1/lib/openhab/dsl/rules/automation_rule.rb:70:in `execute'
```

It didn't get caught by the test.

I thought the docs says `rewinding?` and `fast_forwarding?` but only `rewind?` and `fastforward?` is supported. 

I believe `openhab/dsl/types/types.rb` needs fixing. I am just noting this here because I'm in the middle of working on something else.

**Comment by ccutrer** [comment]
rewinding? and fast_forwarding? are purposely not defined on CommandEvent. And vice versa on PlayerItem - you can't ask it rewind? or fast_forward?. When asking the state itself it doesn't know if it's being used in an imperative context or status context, so it allows both.

Sounds like we can still clean up the tests though.
