### ISSUE TITLE
Exception in thread "Dir Watcher" java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#504]
Whilst looking at tmp/karaf.log in my test environment, I came across this:

```
Exception in thread "Dir Watcher" java.lang.OutOfMemoryError: Java heap space
        at org.jruby.util.ByteList.<init>(ByteList.java:95)
        at org.jruby.RubyString.newStringLight(RubyString.java:460)
        at org.jruby.util.io.EncodingUtils.setStrBuf(EncodingUtils.java:1229)
        at org.jruby.util.io.OpenFile.readAll(OpenFile.java:1698)
        at org.jruby.RubyIO.read(RubyIO.java:3224)
        at org.jruby.RubyIO.read(RubyIO.java:3203)
        at org.jruby.RubyIO.read(RubyIO.java:3993)
        at org.jruby.RubyIO$INVOKER$s$0$3$read.call(RubyIO$INVOKER$s$0$3$read.gen)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:210)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:206)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:372)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:175)
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:316)
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
        at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:80)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:164)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:151)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:198)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:351)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:144)
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:345)
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
        at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:80)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:164)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:151)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:198)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:351)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:144)
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:345)
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
        at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:80)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:164)
```

After this happened, my cucumber scripts won't get loaded anymore, until I restarted openhab. It would work for a bit then stopped again.

I'm on M1 Mac. 

```
$ java --version
openjdk 11.0.12 2021-07-20
OpenJDK Runtime Environment Homebrew (build 11.0.12+0)
OpenJDK 64-Bit Server VM Homebrew (build 11.0.12+0, mixed mode)
```

**Comment by jimtng** [comment]
This *could* be caused by my openjdk on apple silicon (m1 / arm version). I had a lot of issues requiring a restart of openhab. I have since replaced it with Temurin version (for Intel / x64 running under rosetta2 on an M1 mac) and it seems to be much more stable.
