### ISSUE TITLE
Tests against 3.3.0.M2 are flakey

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#548]
I often encountered this error:

```
  Scenario: Item returns all its linked things                                                 # features/items.feature:272
    Given Clean OpenHAB with latest Ruby Libraries                                             # features/step_definitions/openhab.rb:6
      767: unexpected token at '<html>
      <head>
      <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
      <title>Error 404 Not Found</title>
      </head>
      <body><h2>HTTP ERROR 404 Not Found</h2>
      <table>
      <tr><th>URI:</th><td>/rest/rules</td></tr>
      <tr><th>STATUS:</th><td>404</td></tr>
      <tr><th>MESSAGE:</th><td>Not Found</td></tr>
      <tr><th>SERVLET:</th><td>default</td></tr>
      </table>
      <hr><a href="https://eclipse.org/jetty">Powered by Jetty:// 9.4.43.v20210629</a><hr/>
      
      </body>
      </html>
      ' (JSON::ParserError)
      ./features/support/openhab.rb:228:in `block in check_auth'
      ./features/support/openhab.rb:228:in `check_auth'
      ./features/support/openhab.rb:182:in `delete_rules'
      ./features/step_definitions/openhab.rb:7:in `nil'
      features/items.feature:5:in `Clean OpenHAB with latest Ruby Libraries'
```

**Comment by jimtng** [comment]
I suspect that openhab is not ready yet
