### ISSUE TITLE
PersistentHTTP failed intermittently in tests

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#576]
```
  Background:                                      # features/dimmer_item.feature:4
    Given Clean OpenHAB with latest Ruby Libraries # features/step_definitions/openhab.rb:6
      connection refused: localhost:8080 (PersistentHTTP::Error)
      ./features/support/openhab_rest.rb:19:in `rules'
      ./features/support/openhab.rb:184:in `block in delete_rules'
      ./features/support/openhab.rb:229:in `check_auth'
      ./features/support/openhab.rb:184:in `delete_rules'
      ./features/step_definitions/openhab.rb:7:in `nil'
      features/dimmer_item.feature:5:in `Clean OpenHAB with latest Ruby Libraries'
```

**Comment by jimtng** [comment]
This issue is still happening
https://github.com/boc-tothefuture/openhab-jruby/runs/6054149982?check_suite_focus=true

**Comment by jimtng** [comment]
This problem seems persistent. It's still happening
https://github.com/boc-tothefuture/openhab-jruby/runs/6090457694?check_suite_focus=true

I wonder if openhab itself needs to be restarted.
